### ISSUE TITLE
Documentation Improvements

### ISSUE THREAD

**Issue by mwilliams2014** [liferay/clay#1222]
### Introduction

- [ ] A HTML starter template similar to bootstrap getting started-introduction would be helpful or similar to Github's Primer documentation (https://styleguide.github.com/primer/) as Matu suggested.
- [ ] show what components require JS and which don't
- [ ] Clay with ES2015 and Sass is sort of out of place- I feel for an introduction it is too heavy. The intro should focus on the quickest way you can use clay in your site: HTML boiler template and a link to the components: only the quick start section and a link to components
- [ ] components section link is broken

### What is Clay?

- [ ] This info should probably be in the intro. It is very brief and doesn't really need its own section

### Importing the JS Component

- [ ] CDN section should be in introduction instead, as part of the quick start guide and starter template I think

### Web Components

- [ ] CDN doesn't work with web components
- [ ] npm installation didn't work for web components either (I tested in a theme)

Perhaps there is something I'm missing

## Lexicon Core Components

- [ ] inconsistency in language examples: some examples show SOY and JSX, while others show SOY, Web components and HTML. I'm not sure if some components can only be written in the example languages shown, or if those are arbitrary.

### SCSS

- [ ] first sentence contains Spanish "utilitarios" instead of "utilities"
- [ ] Variables, Mixins, and Functions links at top don't work. The Headings markup is missing the matching `id` elements
- [ ] Under each section, there is a link to view all mixins, all variables, and all functions. Since this is the primary documentation site for Clay UI, I would expect to find all that information here, rather than have to search the repos and look through the code myself.

### Class Helpers

- [ ] kind of confusing. Hard to visualize without examples for each section. I know you can right click the examples you do have and view the page source, but providing the HTML markup on the page like you do in the Lexicon core components section would be helpful.

### Satellite Components

- [ ] I'm not sure what satellite components are. for example the button group is identical under satellite components and Lexicon core components. What's the difference? If nothing, why are they listed in two places?

**Comment by matuzalemsteles** [comment]
I'm closing this once we are working on a complete redesign of the site. #1903
