### ISSUE TITLE
Implement ClayDataProvider

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#1330]
Implement a minimal API to cover the use cases of [ClayMultiSelect](https://github.com/liferay/clay/pull/1292) and a generic API to be used in the future in `List`, `Table`, `Dropdown`, `Card`...

### Initial release 
- [x] Receive data locally and remotely
- [x] API for initial data (useful for taking data remotely)
- [x] Option to configure headers

### Long term
- [ ] Cache Control
- [ ] Schema definition?
- [ ] loadingComponent to load a component while fetching data
- [ ] errorComponent to load a component when error occurred in the search of the data
