### ISSUE TITLE
Clay's 3.x - Beyond

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#1712]
Hi guys,

This is a compilation of many proposals that we have had here and some that are spread by other issues and new ideas for Clay 3.x, that means that if we go with that we will be committed to take that forward and make it happen. Before continuing I want to just leave a codename for this version **Beyond** (Suggestions are welcome).

The text is long, I apologize for this, but there are many things I say here, so I ask everyone to read and leave their opinions and let me know if something is unclear.

**Roadmap**
Come back here to find out how we are progressing with this RFC, below is listed what we are approving to move forward with Clay Beyond.

- **Developer relationship**
  - [x] Documentation (#1525, #1903)
  - [x] Blog, release notes... (#1525)
  - [x] Versioning Policy and Semver
- **Workflow**
  - [x] Releases with semver
  - [x] Commit message format (We are starting to adopt #2020 and #2023)
  - [ ] Introduction to new PR labels
  - [x] Documentation - Deploy process
  - [ ] Best Practices TypeScript **(On Hold)**

## Attack points
Although we are starting to build Clay v3 with React and being the most important point of this journey is the best time to review the problems we have experienced in v2 and the lessons we had with him to move on with Clay Beyond.

### Relationship with developers
To date, we have not had a close relationship with Liferay's internal developers who use Clay over changes we make, decisions, and the reasons that led us to do so. It is important to keep this relationship strong so everyone is on the same page.

I think the future of Clay that we hope (in my point of view and perhaps some people's.) Is to be able to build a solid component base and create a community around. To get to that point we need to build some things before:

- **Documentation is an important point to let the devs aware of the changes and good practices:** when using our components and CSS, we should have a closer look at this and everyone should contribute, we can say that is the crux of creating this relationship. You can read more about this proposal that was sent through PR #1525 which introduces the proposal for rewriting the documentation and some new content.
- **Notes on decisions, breaking changes**, changes needed to deploy something: plans for the future are important information to let developers know, the way we should do is not just creating changelogs, they are an important part of this, we can contribute to this is by creating releases notes (something I commented in https://github.com/liferay/clay/issues/1309#issuecomment-441242681) whether in Github or a blog that can create a relationship with readers. (Part of the blog was introduced in the document improvement proposal #1525).
- The **definition of a version policy** is important to pass on the concern we have and the commitment to the developers who use Clay. Following this means that we are introducing gradual depreciation notices and use of the principles of [semantic versioning (semver)](https://semver.org/). Read below for a proposed Versioning Policy for Clay.

### Versioning Policy Proposal
Proposing this goes in conjunction with the use of semver being discussed in #1489, I am compiling some ideas that we discussed there to be summed up in a proposal, you may want to visit the issue to be able to pick up context.

Adopting a Versioning Policy will help us identify which changes are going to come in the next versions and consequently we will have a more detailed roadmap of releases and we will be able to program these releases with more confidence. Currently we do not know what will be in the future or what are the next versions, we usually add anything that appears to the next release (in my vision).

In the adoption of semver we have to identify how long we will continue maintaining the major versions, for example we launched 3.x but in a few months, we already have something prepared for 4.x and 5.x, how long will we keep version 3.x and 4 .x once a bug appears for 3.x. We have to adopt short deadlines based on the Liferay launch cycle, not to bother teams with many changes but with the exception of corrections for Liferay according to the time of its support. With that in mind the proposals below help developers prepare for these changes.

> This reflects for the components of Clay and CSS.

#### Gradual Depreciation Warnings
The use of warnings is an important point to allow developers time to start changing the code, depending on the impact a change can cause, we must adopt the idea of ​​not removing it immediately but sending the warnings first that this change or behavior is removed in the next major versions but in case it is necessary to guarantee compatibility with the new APIs that can be added (Example #1359).

Currently we are adding the warning and removing the behavior, we have to make sure to first add the warnings and to post the changes in a next major version, be it an Alpha or RC version.

#### What counts as breaking change?
We will not change the major version number if some of these changes happen:

- **APIs starting with `unstable_`** (Something similar that React.js uses) Means we are not yet confident about this API and can change at any time but we are working to make it stable. (We can use this a lot for variables in CSS if needed, a use case in [ClayAutocomplete](https://github.com/liferay/clay/blob/2.x-develop/packages/clay-autocomplete/src/ClayAutocomplete.js#L556)) Although we want to deliver a component with a stable API as quickly as possible is a great opportunity to use `unstable` as a proposal to deliver components faster than can be refined over time and that teams can test before reaching something stable.
- **Development warnings** These are messages that should not affect production, we add messages of future API depreaction notices, we can change or add new messages, this gives a margin of safety that the teams can prepare and be informed.
- **Alpha and RC versions** are to precede the next major versions and we can usually release these versions more often if necessary. (this helps the teams that want some correction that causes some breaking change and that they are blocked, will be able to use the RC or Alpha versions)

By doing this we will adopt the semver safely without exponentially growing the number of the main version of the packages.

## Workflow
The introduction of a well-defined workflow gives us assurance to define the next versions, ensuring that we will document our changes and decisions well and maintain a strong relationship with the developers.

### Releases with semver
Following the proposal of Versioning Policy and use of semver, we must follow a flow of releases and maintenance of the major versions and we must reflect this in the organization of our repository.

- Any release of a major version of your code should reflect on the `master` and `develop` branch.
- RC and Alpha versions of a major release release, should keep in their respective branch. `x.x-master` and `x.x-develop`.
- Versions that are being moved to maintenance and old should be moved to branch with their names `x.x-master` and `x.x-develop` and maintained in a short period of time.

### Commit message format
This is something that can help better shape our commits to reflect the changes we make over time and help the people who are reviewing since the commit messages become more apparent when something happened in the change, this is something that was being spoken in #1309.

| Commit message | Release type |
|---|---|
| `fix(@clayui/multi-select) #XXXX: to remove the value when space is entered` | Patch Release |
| `feat(@clayui/dropdown) #XXXX: focus mechanism` | ~~Minor~~ Feature Release |
| `BREAKING CHANGE: remove options API` | ~~Major~~ Breaking Release |

We will not necessarily follow the above to determine the next version of the package, but it shows that it can help us choose the correct format for the commit message.

We can use the [commitizen/cz-cli](https://github.com/commitizen/cz-cli) tool to help with the formats if necessary or we can follow the formats manually.

#### Types
[Angular](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines) uses the format of commitizen / cz-cli to format its commit messages, we can follow this idea with the following formats:

- **feat**: A new feature
- **fix**: A bug fix
- **docs**: Documentation only changes
- **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
- **refactor**: A code change that neither fixes a bug nor adds a feature
- **perf**: A code change that improves performance
- **test**: Adding missing or correcting existing tests
- **chore**: Changes to the build process or auxiliary tools and libraries such as documentation generation

#### Scope
The scope is what is between the type, can mean the location where this change was made, you can try `feat(@clayui/dropdown)`, `feat(@clayui/css)`... not adding scope can symbolize that this change is being made in the infrastructure but you can still specify this in the scope.

### Introduction to new PR labels
Adding these new labels to the PR is super acceptable for us to help identify the next numbering of our package, @carloslancha is currently modifying the PR title to symbolize this, I think we can use the labels in our favor until we can identify a tool that we help with that. Something like [semantic release](https://github.com/semantic-release/semantic-release) as [I said in other comments](https://github.com/liferay/clay/issues/1309#issuecomment-440096876).

| Label | Notes |
|---|---|
| New API | Symbolize the addition of a new API to the component |
| API Changed | Symbolize the API change to the component  |
| Next Note | Symbolize that the changes included in the PR will be informed in the next release note (or blog) with due reasons |

> We can still include in the PR's the `breaking change` label that we currently have.

### Documentation
Once we are moving forward with #1525, we can begin to include the documentation in our routines. For a while the documentation is well forgotten and everyone should be committed to keeping the documents updated as soon as they make a change requesting documentation, we should be committed to adding good practices for using our components.

#### Deploy process
The #1170 proposal will help us get three types of documentation environments: `dev`, `prod`, `pr`.

WeDeploy is being discontinued so it may be a good time to choose a platform that can help us deploy it now, a suggestion would be to use [netlify](https://www.netlify.com) React.js uses to deploy the environment for reactjs.org.

### Best Practices TypeScript
We are introducing the use of TypeScript but we need to set standards for best practices. We have a ticket internally to set this https://issues.liferay.com/browse/IFI-552 see for more context. Leaving it on On Hold.

- https://github.com/sw-yx/react-typescript-cheatsheet/blob/master/README.md

**Comment by diegonvs** [comment]
I totally agree with all points that have been pointed up by Matu and here is my 2cents:

- I really loved the idea to enhance our semvar to keep people updated about Breaking Changes but we need to have attention about creating too much versions when breaking changes. We can use a `unstable_ ` like in the functions name and when we collected a number of these unstable functions, we can proceed with a new major semvar

**Comment by wincent** [comment]
Thanks for writing this up @matuzalemsteles.

> Commit message format

On this subject, we were just talking about this in the liferay-js-themes-toolkit repo, because we have found both there and in alloy-editor that `github_changelog_generator` doesn't work well with multiple branches (lots of detail about the problems in https://github.com/liferay/liferay-js-themes-toolkit/issues/221). In both repos we are actively making releases to both previous and current development branches (v8 and v9 in the case of the themes toolkit and v1.5 and v2.0 in the case of AlloyEditor), which means that some of our release notes have been subtly (or not so subtly) broken, or just cooked up by hand, which isn't great either.

In themes toolkit I made [this script](https://github.com/liferay/liferay-js-themes-toolkit/blob/744343474eb3fd75c00ce3ef9d99cd72900797e0/scripts/changelog.js) that replaces `github_changelog_generator` in the simplest possible terms, and created https://github.com/liferay/liferay-js-themes-toolkit/issues/258 to discuss the possibility of extracting metadata by using a structured format for commit messages, just like you brought up here. Useful links are the "[Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)" specification, the [full list of prefixes](https://github.com/commitizen/conventional-commit-types/blob/master/index.json) ("feat", "fix" etc). Especially interesting is that there is [a GitHub bot](https://github.com/apps/semantic-pull-requests) that we could add that would make sure all of our PRs conform, and [it's configurable](https://github.com/probot/semantic-pull-requests). The nice thing about the bot is it wouldn't require any contributor to install anything in order to participate in the workflow (although nothing would stop you from doing so, if you wanted to).

**Comment by matuzalemsteles** [comment]
hey @wincent thanks for bringing this, we are also facing these changelog problems mainly with Lerna. I had no glance at full spec on the **Conventional Commits** website, thank you for bringing this. I really like the idea of ​​using the bot will help us make sure to always use the format. I support use 🙂.

We can fine-tune your changelog generator to maybe set the next version based on the format ... just a thought (even though we have the semantic-release tool).

**Comment by matuzalemsteles** [comment]
hey guys, sorry for duplicate comment, but I just want to show an image I was looking for when I was writing this RFC and I ended up finding it today 🙂.

This image represents the release and maintenance cycle of a legacy version of Node.js, something I wanted to be able to get here with Clay, using the best practices of using **Versioning Policy** with semver. This is also related to my comments in **Releases with semver**.

More details https://github.com/nodejs/Release

<img src="https://pbs.twimg.com/media/D2rtT6UWwAA4Ieb?format=jpg" />

**Comment by bryceosterhaus** [comment]
I think we have made good progress. Going to close unless more comes up.

btw this is helpful for the TS+react best practices. https://github.com/typescript-cheatsheets/react-typescript-cheatsheet
