### ISSUE TITLE
[Migration Docs] next.clayui.com v3

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#1903]
This is a list of documents that need to be crafted to be added to the new `next.clayui.com` documentation. The CSS documentation that is present in the **CSS Framework** and **Lexicon Core Components** sessions at clayui.com will join the documentation in the new CSS session at next.clayui.com.

Once we have that complete we will redirect all traffic from CSS documentation from site v2 to the new v3 documentation.

> If you'd like to help migrate add your name in front of the documents you're working on.

### CSS
The session brings together good practice guides on using CSS, information on the Lexicon standard and how you can go further.

- [ ] **Paver**
- [ ] **Content**
  - [ ] Images
  - [x] Typography
- [x] **Grid**
- [ ] **Components**
  - [x] Alerts
  - [x] Badges (#2020)
  - [x] Buttons (#2020)
  - [x] Button Groups (#2020)
  - [x] Cards (#2044)
  - [x] Dropdown Menu (#2047)
  - [x] Forms (@matuzalemsteles)
    - [x] Toggle Switch (#2028)
    - [x] Checkbox, Radio (#2028)
    - [x] Color Picker (#2040)
    - [x] Date & Time Pickers (#2042)
    - [x] Form Group (#2045)
    - [x] Forms Hierarchy (#2045)
    - [x] Multi Select
    - [x] Multi Step Form (#2045)
    - [x] Text Input (#2028)
    - [x] Text Input Autocomplete (#2028)
    - [x] Text Input Group (#2028)
    - [x] Text Input Localizable (#2028)
  - [x] Icons (#2027)
  - [x] Labels (#2027)
  - [x] Link (#2027)
  - [x] List (#2027)
  - [x] Loading Indicator (#2027)
  - [x] Modals (#2050)
  - [x] Navigation (#2108)
   - [x] Pagination
   - [x] Popovers and Tooltips (#2038)
   - [x] Progress Bars (#2036)
   - [x] Sidebar
     - [x] Info Panel
   - [x] Stickers (#2030)
   - [x] Table
     - [x] Inline Edit Table
     - [x] Table
   - [x] Tabs (#2031)
   - [x] Timelines (#2033)
   - [x] Toolbars (#2109)
     - [x] Management Toolbar
- [x] **Utilities**
  - [x] Autofit
  - [x] Inline Item

### React Components
The session is unique to component documentation made in React, adding guides to best practices, variations, API, and unique playground for quick interaction.

- [x] Clay Alert
- [x] Clay Autocomplete
- [x] Clay Badge
- [x] Clay Button
- [x] Clay Card and Card Grid
- [ ] Clay Charts
- [x] Clay Checkbox
- [x] Clay Color Picker
- [x] Clay Date Picker
- [x] Clay Data Provider
- [x] Clay Dropdown
- [x] Clay Icon
- [x] Clay Label
- [x] Clay Link
- [x] Clay List
- [x] Clay Loading Indicator
- [ ] Clay Management Toolbar
- [x] Clay Modal
- [ ] Clay Multi Select
- [x] Clay Navigation Bar
- [x] Clay Pagination
- [ ] Clay Pagination Bar
- [x] Clay Progress Bar
- [x] Clay Radio Group
- [x] Clay Sticker
- [x] Clay Table
- [ ] Clay Time Picker

### Additional docs
Additional documents to generate more content for the developer and generate a better understanding of how we work, the principles and ways to contribute to the project.

- [ ] Introduction
- [ ] Web Components
- [ ] Accessibility
- [ ] Principles
- [ ] How to Contribute
- [ ] Versioning Policy
- [x] Migrate the Clay components from v2 to v3 (**In progress...**)

**Comment by matuzalemsteles** [comment]
hey @pat270 I would appreciate your help to organize the CSS session and also add more informative content in the documentation. Let me know if I've forgotten any documents.

@bryceosterhaus I'm working to merge the base infrastructure of the new site to #1525 so we can start creating the components documents in React, I'll appreciate your help so we can create these documents with the maximum information and good practices we discussed in PR's .

**Comment by matuzalemsteles** [comment]
I'm closing this and will open new tickets that reflects the new documentation of the components.
