### ISSUE TITLE
@clayui/css Convert mixins to use generic clay-css mixin

### ISSUE THREAD

**Issue by pat270** [liferay/clay#3075]
Mixins like `clay-button-variant`, `clay-close`, and `clay-dropdown-menu-variant` should leverage the `clay-css` mixin so we won't need to repeat property declarations for each mixin. It also allows for a wider range of css properties to be passed in.
- [x] clay-sticker-variant #3160
- [x] clay-tbar-variant #3162
- [x] clay-autofit-row #3163
- [x] clay-panel-variant #3159
- [x] clay-modal-variant #3155
- [x] clay-dropdown-menu-variant #3154
- [x] clay-dropdown-item-variant #3154
- [x] clay-input-group-stacked #3103
- [x] clay-input-group-text-variant #3103
- [x] clay-after-highlight-variant #3102
- [x] clay-row #3101
- [x] clay-container #3101
- [x] clay-text-typography #3099
- [x] clay-link #3098
- [x] clay-close #3097
- [x] clay-button-variant #3093
