### ISSUE TITLE
@clayui/css Mixins deprecated keys should win to preserve backward compatibility

### ISSUE THREAD

**Issue by pat270** [liferay/clay#3164]
The Sass `map-merge` function prioritizes the 2nd map's values over the 1st. These mixins have the deprecated keys passed in the first parameter of `map-merge` causing deprecated key value pairs to be overwritten by the new ones. This causes themes relying on the old names to break.

- [x] clay-input-group-stacked #3165
- [x] clay-input-group-text-variant #3165
- [x] clay-after-highlight-variant #3168
- [x] clay-container #3169
- [x] clay-text-typography #3170
- [x] clay-link #3170
- [x] clay-close #3171
- [x] clay-button-variant #3172
